// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otcachwiyjgqoxdkfobu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90Y2FjaHdpeWpncW94ZGtmb2J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwNTY0NTAsImV4cCI6MjA2NjYzMjQ1MH0.SVzz-GGhR2t0Km8rWRaRbj5CM0SSBFMPM70gE1w4b2s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);